Docker dev cleanups

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -37,21 +37,15 @@ ARG POETRY_VERSION=1.7.1 \
 RUN curl -L https://install.python-poetry.org/ | python3
 ENV PATH="${POETRY_HOME}/bin:${PATH}"
 
-# Add basic files needed for poetry
-RUN mkdir -p /app/vintage_pi_tv \
-    && touch /app/README.md /app/vintage_pi_tv/__init__.py
+# Add basic files needed for poetry (need vintage_pi_tv/__init__.py to install poetry scripts)
+RUN mkdir -p /app/vintage_pi_tv && touch /app/vintage_pi_tv/__init__.py
 WORKDIR /app
 COPY pyproject.toml poetry.lock /app/
 
-# Install deps
-RUN poetry install
-
-# Copy over image files
-COPY docker/entrypoint.sh /
-COPY docker/daemons.conf /etc/supervisor/conf.d/
-COPY docker/nginx.conf /etc/nginx/sites-enabled/default
+# Install deps (comment out readme in pyproject to prevent failure)
+RUN sed -i 's/^readme = /#\0/' pyproject.toml && poetry install
 
 # Set up entrypoint which stats Xvfb, x11vnc and nginx serving noVNC
 ENV DISPLAY=:0
 ENTRYPOINT [ "/entrypoint.sh" ]
-CMD [ "/bin/bash" ]
+CMD [ "/bin/sh", "-c", "while ! [ -S /tmp/.X11-unix/X0 ]; do sleep 0.05 ; done ; exec tv" ]
